name: roomart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  carousel_slider: ^3.0.0
  color_to_material: ^0.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  dio: ^4.0.0
  flutter_bloc: ^7.0.0
  flutter_html: ^1.2.0
  flutter_slidable: ^0.6.0
  flutter_touch_spin: ^2.0.0-nullsafety.1
  fluttertoast: ^8.0.6
  freezed_annotation: ^0.12.0
  get: ^4.1.4
  get_it: ^5.0.6
  get_storage: ^2.0.2
  injectable: ^1.0.7
  intl: ^0.17.0
  json_annotation: ^3.1.1
  pull_to_refresh: ^1.6.5
  search_widget: ^1.0.2
  url_launcher: ^6.0.3
  webview_flutter: ^1.0.7
  flutter_launcher_icons: ^0.8.1
  rename: ^1.3.1
  cached_network_image: ^2.5.1
  firebase_core: "^0.7.0"
  firebase_messaging: "^8.0.0-dev.15"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  freezed: ^0.12.7
  injectable_generator: ^1.0.7
  change_app_package_name: ^1.0.0

  json_serializable: ^3.5.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/broken_image.png
    - assets/promotion.png
    - assets/roomart_logo.png
    - assets/file/

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"



#     flutter pub run rename --bundleId com.onatcipli.networkUpp
#     flutter pub run rename --appname "Network Upp"
#     flutter pub run flutter_launcher_icons:main
