// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'transaction_detail_v1.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_TransactionDetailV1 _$_$_TransactionDetailV1FromJson(
    Map<String, dynamic> json) {
  return _$_TransactionDetailV1(
    salesOrderDetailId: json['sales_order_detail_id'] as String?,
    salesOrderId: json['sales_order_id'] as String?,
    indexNo: json['index_no'] as String?,
    itemId: json['item_id'] as String?,
    itemCode: json['item_code'] as String?,
    itemName: json['item_name'] as String?,
    description: json['description'] as String?,
    unitId: json['unit_id'] as String?,
    unitCode: json['unit_code'] as String?,
    taxId: json['tax_id'] as String?,
    taxAmount: json['tax_amount'] as String?,
    subTotalTax: json['sub_total_tax'] as String?,
    discount: json['discount'] as String?,
    subTotalDisc: json['sub_total_disc'] as String?,
    qty: json['qty'] as String?,
    qtyBase: json['qty_base'] as String?,
    itemPrice: json['item_price'] as String?,
    subTotal: json['sub_total'] as String?,
    costPerUnit: json['cost_per_unit'] as String?,
    deliveredQty: json['delivered_qty'] as String?,
    closed: json['closed'] as String?,
    projectId: json['project_id'] as String?,
    departmentId: json['department_id'] as String?,
    employeeId: json['employee_id'] as String?,
    quotationId: json['quotation_id'] as String?,
    quotationDetailId: json['quotation_detail_id'] as String?,
    barcode: json['barcode'] as String?,
    itemSku: json['item_sku'] as String?,
    itemSkuName: json['item_sku_name'] as String?,
    vendorItemCode: json['vendor_item_code'] as String?,
    vendorItemName: json['vendor_item_name'] as String?,
    itemType: json['item_type'] as String?,
    kategoriId: json['kategori_id'] as String?,
    purchaseUnitId: json['purchase_unit_id'] as String?,
    purchaseTaxId: json['purchase_tax_id'] as String?,
    preferedVendorId: json['prefered_vendor_id'] as String?,
    minPrice: json['min_price'] as String?,
    isFixedPrice: json['is_fixed_price'] as String?,
    itemPicture: json['item_picture'] as String?,
    lastPurchasePrice: json['last_purchase_price'] as String?,
    lastPurchaseCurr: json['last_purchase_curr'] as String?,
    lastPurchaseRate: json['last_purchase_rate'] as String?,
    profitMargin: json['profit_margin'] as String?,
    minimumStock: json['minimum_stock'] as String?,
    reorderPoint: json['reorder_point'] as String?,
    maximumStock: json['maximum_stock'] as String?,
    rackLocation: json['rack_location'] as String?,
    warehouseId: json['warehouse_id'] as String?,
    deliveryType: json['delivery_type'] as String?,
    itemStatusCodeId: json['item_status_code_id'] as String?,
    statusColor: json['status_color'] as String?,
    discountAmount: json['discount_amount'] as String?,
    createBy: json['create_by'] as String?,
    addDate: json['add_date'] as String?,
    updateDate: json['update_date'] as String?,
    lastAdjustment: json['last_adjustment'] as String?,
    size: json['size'] as String?,
    color: json['color'] as String?,
    sizeUnit: json['size_unit'] as String?,
    unitConversion: json['unit_conversion'] as String?,
    manufacturer: json['manufacturer'] as String?,
    trackSerialNo: json['track_serial_no'] as String?,
    trackBatchNo: json['track_batch_no'] as String?,
    itemStatus: json['item_status'] as String?,
    inventoryAccount: json['inventory_account'] as String?,
    salesAccount: json['sales_account'] as String?,
    salesReturnAccount: json['sales_return_account'] as String?,
    itemDiscountAccount: json['item_discount_account'] as String?,
    cogsAccount: json['cogs_account'] as String?,
    purchaseReturnAccount: json['purchase_return_account'] as String?,
    expenseAccount: json['expense_account'] as String?,
    unbilledGoodsAccount: json['unbilled_goods_account'] as String?,
    isConsignment: json['is_consignment'] as String?,
    isDiscontinue: json['is_discontinue'] as String?,
    displayStore: json['display_store'] as String?,
    displayDesc: json['display_desc'] as String?,
    tags: json['tags'] as String?,
    weight: json['weight'] as String?,
    volume: json['volume'] as String?,
    brand: json['brand'] as String?,
  );
}

Map<String, dynamic> _$_$_TransactionDetailV1ToJson(
        _$_TransactionDetailV1 instance) =>
    <String, dynamic>{
      'sales_order_detail_id': instance.salesOrderDetailId,
      'sales_order_id': instance.salesOrderId,
      'index_no': instance.indexNo,
      'item_id': instance.itemId,
      'item_code': instance.itemCode,
      'item_name': instance.itemName,
      'description': instance.description,
      'unit_id': instance.unitId,
      'unit_code': instance.unitCode,
      'tax_id': instance.taxId,
      'tax_amount': instance.taxAmount,
      'sub_total_tax': instance.subTotalTax,
      'discount': instance.discount,
      'sub_total_disc': instance.subTotalDisc,
      'qty': instance.qty,
      'qty_base': instance.qtyBase,
      'item_price': instance.itemPrice,
      'sub_total': instance.subTotal,
      'cost_per_unit': instance.costPerUnit,
      'delivered_qty': instance.deliveredQty,
      'closed': instance.closed,
      'project_id': instance.projectId,
      'department_id': instance.departmentId,
      'employee_id': instance.employeeId,
      'quotation_id': instance.quotationId,
      'quotation_detail_id': instance.quotationDetailId,
      'barcode': instance.barcode,
      'item_sku': instance.itemSku,
      'item_sku_name': instance.itemSkuName,
      'vendor_item_code': instance.vendorItemCode,
      'vendor_item_name': instance.vendorItemName,
      'item_type': instance.itemType,
      'kategori_id': instance.kategoriId,
      'purchase_unit_id': instance.purchaseUnitId,
      'purchase_tax_id': instance.purchaseTaxId,
      'prefered_vendor_id': instance.preferedVendorId,
      'min_price': instance.minPrice,
      'is_fixed_price': instance.isFixedPrice,
      'item_picture': instance.itemPicture,
      'last_purchase_price': instance.lastPurchasePrice,
      'last_purchase_curr': instance.lastPurchaseCurr,
      'last_purchase_rate': instance.lastPurchaseRate,
      'profit_margin': instance.profitMargin,
      'minimum_stock': instance.minimumStock,
      'reorder_point': instance.reorderPoint,
      'maximum_stock': instance.maximumStock,
      'rack_location': instance.rackLocation,
      'warehouse_id': instance.warehouseId,
      'delivery_type': instance.deliveryType,
      'item_status_code_id': instance.itemStatusCodeId,
      'status_color': instance.statusColor,
      'discount_amount': instance.discountAmount,
      'create_by': instance.createBy,
      'add_date': instance.addDate,
      'update_date': instance.updateDate,
      'last_adjustment': instance.lastAdjustment,
      'size': instance.size,
      'color': instance.color,
      'size_unit': instance.sizeUnit,
      'unit_conversion': instance.unitConversion,
      'manufacturer': instance.manufacturer,
      'track_serial_no': instance.trackSerialNo,
      'track_batch_no': instance.trackBatchNo,
      'item_status': instance.itemStatus,
      'inventory_account': instance.inventoryAccount,
      'sales_account': instance.salesAccount,
      'sales_return_account': instance.salesReturnAccount,
      'item_discount_account': instance.itemDiscountAccount,
      'cogs_account': instance.cogsAccount,
      'purchase_return_account': instance.purchaseReturnAccount,
      'expense_account': instance.expenseAccount,
      'unbilled_goods_account': instance.unbilledGoodsAccount,
      'is_consignment': instance.isConsignment,
      'is_discontinue': instance.isDiscontinue,
      'display_store': instance.displayStore,
      'display_desc': instance.displayDesc,
      'tags': instance.tags,
      'weight': instance.weight,
      'volume': instance.volume,
      'brand': instance.brand,
    };
